import { Heart, Repeat2, MessageCircle, Bookmark } from "lucide-react";

const viralPosts = [
  {
    handle: "@growth_sarah",
    avatar: "S",
    content: "I spent 6 months studying why tweets go viral.\n\nHere's the framework nobody talks about:\n\n→ Pattern interrupt in first 3 words\n→ Emotional polarity (not neutral)\n→ Identity-level resonance\n→ Low-friction engagement hooks\n\nBookmark this.",
    likes: "12.4K",
    retweets: "3.2K",
    replies: "847",
    bookmarks: "8.1K",
    tag: "Generated by AI",
  },
  {
    handle: "@techfounder_mk",
    avatar: "M",
    content: "Hot take: Your content isn't boring.\n\nYour hooks are.\n\nThe difference between 50 views and 50K views is the first 7 words.",
    likes: "8.7K",
    retweets: "2.1K",
    replies: "423",
    bookmarks: "5.3K",
    tag: "Generated by AI",
  },
  {
    handle: "@mindsetceo",
    avatar: "A",
    content: "Stop writing tweets.\n\nStart writing scroll-stoppers.\n\n• Curiosity gaps > information\n• Questions > statements\n• Stories > lectures\n• Tension > resolution\n\nYour audience doesn't owe you attention. Earn it.",
    likes: "21.3K",
    retweets: "6.8K",
    replies: "1.2K",
    bookmarks: "14.7K",
    tag: "Generated by AI",
  },
  {
    handle: "@contentqueen",
    avatar: "J",
    content: "The algorithm doesn't care about your feelings.\n\nIt cares about:\n— Dwell time\n— Saves\n— Replies with 3+ words\n— Profile clicks\n\nOptimize for these. Watch everything change.",
    likes: "15.9K",
    retweets: "4.4K",
    replies: "956",
    bookmarks: "11.2K",
    tag: "Generated by AI",
  },
  {
    handle: "@buildinpublic",
    avatar: "R",
    content: "I asked AI to rewrite my worst-performing tweet.\n\nOriginal: 12 likes.\nRewritten: 4,200 likes.\n\nSame idea. Better hook. That's the whole game.",
    likes: "6.2K",
    retweets: "1.8K",
    replies: "312",
    bookmarks: "3.9K",
    tag: "Generated by AI",
  },
  {
    handle: "@nikdev_",
    avatar: "N",
    content: "Your thread won't go viral because:\n\n1. The first tweet doesn't create tension\n2. You're teaching, not storytelling\n3. No open loop between tweets\n4. The CTA is \"follow me\" instead of value\n\nFix these. Thank me later.",
    likes: "18.1K",
    retweets: "5.6K",
    replies: "1.4K",
    bookmarks: "12.8K",
    tag: "Generated by AI",
  },
];

export function ViralProofs() {
  return (
    <section className="py-24 overflow-hidden">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <p className="text-xs font-mono text-primary tracking-widest uppercase mb-4">Proof</p>
          <h2 className="text-3xl md:text-4xl font-bold mb-4">AI-Generated. Viral-Ready.</h2>
          <p className="text-base text-muted-foreground max-w-xl mx-auto">
            Real outputs from our engine. Every post below was generated, optimized, and formatted by the AI.
          </p>
        </div>

        <div className="columns-1 md:columns-2 lg:columns-3 gap-4 space-y-4">
          {viralPosts.map((post, i) => (
            <div
              key={i}
              className="break-inside-avoid rounded-xl border border-border bg-card p-5 hover:border-primary/30 transition-colors duration-200"
            >
              <div className="flex items-center gap-3 mb-4">
                <div className="h-9 w-9 rounded-full bg-secondary flex items-center justify-center text-sm font-semibold text-foreground">
                  {post.avatar}
                </div>
                <div>
                  <div className="text-sm font-medium text-foreground">{post.handle}</div>
                  <div className="text-[10px] font-mono text-primary">{post.tag}</div>
                </div>
              </div>

              <p className="text-sm text-foreground leading-relaxed whitespace-pre-line mb-5">
                {post.content}
              </p>

              <div className="flex items-center gap-5 text-muted-foreground">
                <span className="flex items-center gap-1.5 text-xs">
                  <MessageCircle className="h-3.5 w-3.5" />
                  {post.replies}
                </span>
                <span className="flex items-center gap-1.5 text-xs">
                  <Repeat2 className="h-3.5 w-3.5" />
                  {post.retweets}
                </span>
                <span className="flex items-center gap-1.5 text-xs">
                  <Heart className="h-3.5 w-3.5" />
                  {post.likes}
                </span>
                <span className="flex items-center gap-1.5 text-xs">
                  <Bookmark className="h-3.5 w-3.5" />
                  {post.bookmarks}
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
